app:
  enabled: true
  resources:
    requests:
      cpu: 0.2
      memory: 256Mi
    limits:
      cpu: 1
      memory: 4Gi
  env:
    - name: APP_BASE_URL
      value: "https://{{ $.Values.global.host }}"
  envFrom:
    - secretRef:
        name: pg-user
    - secretRef:
        name: app-sealed-secret
    - configMapRef:
        name: app-configmap
  probesPath: /api/healthz
  replicas: 1
  imagePackage: app

app-form:
  enabled: true
  host: "formulaire-{{ $.Values.global.host }}"
  resources:
    requests:
      cpu: 0.2
      memory: 256Mi
    limits:
      cpu: 1
      memory: 4Gi
  env:
    - name: APP_BASE_URL
      value: "https://formulaire-{{ $.Values.global.host }}"
  envFrom:
    - secretRef:
        name: pg-user-form
    - secretRef:
        name: app-sealed-secret
    - configMapRef:
        name: app-configmap
  probesPath: /api/healthz
  replicas: 1
  imagePackage: form

metabase:
  enabled: false

oauth2-proxy:
  enabled: false
