apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-scheduler
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  schedule: "0 */12 * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          securityContext:
            fsGroup: 1000
            runAsUser: 1000
            runAsGroup: 1000
          containers:
            - name: scheduler
              image: "{{ or .Values.registry .Values.global.registry }}/{{ .Values.global.imageProject }}/{{ .Values.global.imageRepository }}/scheduler:{{ .Values.global.imageTag }}"
              command: ["/scheduler.sh"]
              env:
                - name: TARGET_URL
                  value: "https://{{ $.Values.global.host }}/api/scheduler"
              resources:
                requests:
                  cpu: 10m
                  memory: 32Mi
                limits:
                  cpu: 50m
                  memory: 64Mi
