apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    component: ds-cronjob
    application: enfants-du-spectacle
  name: ds-cronjob
spec:
  schedule: 10 * * * *
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            component: ds-cronjob
            application: enfants-du-spectacle
          name: ds-cronjob
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cronjob-container
              image: curlimages/curl:7.84.0
              command:
                - /bin/sh
                - -c
              args:
                - |
                  curl -X GET "https://enfants-du-spectacle.fabrique.social.gouv.fr/api/dsapi"
                  curl -X GET "https://enfants-du-spectacle-preprod.dev.fabrique.social.gouv.fr/api/dsapi"
              envFrom:
                - secretRef:
                    name: backend-sealed-secret
                - configMapRef:
                    name: backend-configmap
