kind: ConfigMap
apiVersion: v1
metadata:
  name: app-configmap
data:
  NODE_ENV: "production"
  EMAIL_FROM: "Enfants du Spectacle [PREPROD] <enfantsduspectacle@diffusion.fabrique.social.gouv.fr>"
  DEMARCHE_NUMBER: "55315"
