kind: ConfigMap
apiVersion: v1
metadata:
  name: app-configmap
data:
  NODE_ENV: "production"
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
  EMAIL_FROM: "Enfants du Spectacle [PREPROD] <enfantsduspectacle@diffusion.fabrique.social.gouv.fr>"
  DEMARCHE_NUMBER: "55315"
  API_URL_INSTRUCTEUR: "https://enfants-du-spectacle-preprod.ovh.fabrique.social.gouv.fr/api/sync"
  API_URL_SDP: "https://formulaire-enfants-du-spectacle-preprod.ovh.fabrique.social.gouv.fr/api/sync"
  URL_SDP: "https://formulaire-enfants-du-spectacle-preprod.ovh.fabrique.social.gouv.fr"
  URL_INSTRUCTEUR: "https://enfants-du-spectacle-preprod.ovh.fabrique.social.gouv.fr"
  NEXT_PUBLIC_AGENT_HJID: "3347456"
  NEXT_PUBLIC_AGENT_HJSV: "6"
  NEXT_PUBLIC_FORMULAIRE_HJID: "3347496"
  NEXT_PUBLIC_FORMULAIRE_HJSV: "6"
  NEXT_PUBLIC_MATOMO_URL: "https://matomo.fabrique.social.gouv.fr/"
  NEXT_PUBLIC_MATOMO_SITE_AGENT_ID: "85"
  NEXT_PUBLIC_MATOMO_SITE_FORMULAIRE_ID: "84"
  NEXT_PUBLIC_API_URL_SDP: "https://formulaire-enfants-du-spectacle-preprod.dev.fabrique.social.gouv.fr/api/sync"
