app:
  addVolumes:
    - docs
  replicas: 1 # temporary, need to delete when swr fixed
app-form:
  addVolumes:
    - docs-form
  replicas: 1 # temporary, need to delete when swr fixed

metabase:
  enabled: true
  ingress:
    enabled: false
  envFrom:
    - configMapRef:
        name: metabase-configmap
    - secretRef:
        name: metabase-db-user

oauth2-proxy:
  host: "metabase-eds.fabrique.social.gouv.fr"
  enabled: true
  upstream: http://metabase
  envFrom:
    - configMapRef:
        name: oauth2-proxy-configmap
    - secretRef:
        name: oauth2-proxy-sealed-secret
  # additionalArgs:
  #   - --skip-auth-route
  #   - ^/public/.*,^/app/dist/.*,^/api/public/.*,^/api/session/.*,^/app/assets/.*
