components:
  jobs: true

app:
  needs: [db]
  replicas: 1
  envFrom:
    - secretRef:
        name: pg-user-{{ .Values.global.branchSlug }}

jobs:
  runs:
    - name: db
      use: SocialGouv/actions/uses/create-db@v1
      with:
        pgAdminSecretRefName: azure-pg-admin-user