import { z } from 'zod';

export const JustificatifEnfantSchema = z.enum([
  'LIVRET_FAMILLE',
  'AUTORISATION_PARENTALE',
  'SITUATION_PARTICULIERE',
  'CONTRAT',
  'CERTIFICAT_SCOLARITE',
  'AVIS_MEDICAL',
  'DECLARATION_HONNEUR',
  'BON_PRISE_EN_CHARGE',
  'AUTORISATION_PRISE_EN_CHARGE',
]);
