import { z } from 'zod';

export const NatureCachetSchema = z.enum([
  'CACHET_TOURNAGE',
  'CACHET_DOUBLAGE',
  'CACHET_REPRESENTATION',
  'CACHET_REPETITION',
  'CACHET_HORAIRE',
  'CACHET_SECURITE',
  'CACHET_POST_SYNCHRO',
  'CACHET_CAPTATION',
  'CACHET_SPECTACLE_VIVANT',
  'CACHET_RETAKE',
  'AUTRE_GARANTIE',
  'AUTRE_ADDITIONNELLE',
]);
