import { z } from 'zod';

export const CategorieDossierSchema = z.enum([
  'LONG_METRAGE',
  'COURT_METRAGE',
  'TELEFILM',
  'SERIE',
  'EMISSION_TV',
  'DOCUMENTAIRE_FICTIONNEL',
  'CLIP',
  'THEATRE',
  'DOUBLAGE',
  'MUSIQUE_STUDIO',
  'COMEDIE_MUSICALE',
  'CONCERT',
  'OPERA',
  'BALLET',
  'DANSE',
  'CIRQUE',
  'RADIO',
  'PHOTO',
  'FILM_INSTITUTIONNEL',
  'JEU_VIDEO',
  'VIDEO_EN_LIGNE',
  'AUTRE',
]);
