import { z } from 'zod';

export const EnfantScalarFieldEnumSchema = z.enum([
  'id',
  'prenom',
  'nom',
  'dateNaissance',
  'typeEmploi',
  'nomPersonnage',
  'periodeTravail',
  'nombreJours',
  'contexteTravail',
  'montantCachet',
  'nombreCachets',
  'nombreLignes',
  'remunerationsAdditionnelles',
  'remunerationTotale',
  'justificatifs',
  'dossierId',
  'cdc',
  'adresseEnfant',
  'nomRepresentant1',
  'prenomRepresentant1',
  'adresseRepresentant1',
  'telRepresentant1',
  'mailRepresentant1',
  'adresseRepresentant2',
  'nomRepresentant2',
  'prenomRepresentant2',
  'telRepresentant2',
  'mailRepresentant2',
  'externalId',
  'typeConsultation',
  'typeConsultationMedecin',
  'dateConsultation',
  'checkTravailNuit',
  'textTravailNuit',
]);
