projectName: enfants-du-spectacle
dependencies:
  fabrique:
    extends:
      - name: buildkit-service
      - name: ovh
        ifEnv: [dev, preprod]
    dependencies:
      contrib:
        preDeploy:
          importSecrets:
            options:
              secrets:
                enfants-du-spectacle-dev-backups-access-key:
                enfants-du-spectacle-prod-backups-access-key:

