app:
  ~chart: app
  ~needs: [pg]
  imagePackage: app
  annotations:
    oblik.socialgouv.io/min-request-cpu: "200m"
    oblik.socialgouv.io/min-request-memory: "512Mi"
  env:
    - name: APP_BASE_URL
      value: "https://{{ $.Values.global.host }}"
  envFrom:
    - secretRef:
        name: pg-app
    - secretRef:
        name: app-sealed-secret
    - configMapRef:
        name: app-configmap
  probesPath: /api/healthz
  readinessProbe:
    httpGet:
      path: /api/healthz
      port: http
    timeoutSeconds: 3 # otherwise we get instability of the readiness probe
  ingress:
    customHeaders:
      "Content-Security-Policy": "default-src 'none'; manifest-src 'self' https://*.gouv.fr; connect-src 'self' https://*.gouv.fr; media-src 'self'; font-src 'self' data:; img-src 'self' data:; script-src 'self' https://*.gouv.fr 'unsafe-inline'; frame-src 'self' https://*.gouv.fr; style-src 'self' 'unsafe-inline'"
      "X-Frame-Options": "deny"
      "X-XSS-Protection": "1; mode=block"
      "X-Content-Type-Options": "nosniff"
  startupProbe:
    failureThreshold: 48
    periodSeconds: 5
    httpGet:
      path: /api/healthz
      port: http

form:
  ~chart: app
  ~needs: [pg]
  imagePackage: form
  host: "formulaire-{{ $.Values.global.host }}"
  annotations:
    oblik.socialgouv.io/min-request-cpu: "200m"
    oblik.socialgouv.io/min-request-memory: "512Mi"
  env:
    - name: APP_BASE_URL
      value: "https://formulaire-{{ $.Values.global.host }}"
    - name: START_SCRIPT
      value: "start-prod"
  envFrom:
    - secretRef:
        name: pg-app
    - secretRef:
        name: app-sealed-secret
    - configMapRef:
        name: app-configmap
  probesPath: /api/healthz
  readinessProbe:
    httpGet:
      path: /api/healthz
      port: http
    timeoutSeconds: 3 # prevent instability of the readiness probe
  startupProbe:
    failureThreshold: 48
    periodSeconds: 5
    httpGet:
      path: /api/healthz
      port: http
  ingress:
    customHeaders:
      "Content-Security-Policy": "default-src 'none'; manifest-src 'self' https://*.gouv.fr; connect-src 'self' https://*.gouv.fr; media-src 'self'; font-src 'self' data:; img-src 'self' data:; script-src 'self' https://*.gouv.fr 'unsafe-inline'; frame-src 'self' https://*.gouv.fr; style-src 'self' 'unsafe-inline'"
      "X-Frame-Options": "deny"
      "X-XSS-Protection": "1; mode=block"
      "X-Content-Type-Options": "nosniff"

pg:
  ~chart: pg
  postgresqlParameters:
    max_connections: "1000"
