app:
  needs: [db]
  envFrom:
    - secretRef:
        name: pg-user-{{ .Values.global.branchSlug }}

jobs:
  enabled: true
  runs:
    - name: db
      use: SocialGouv/kube-workflow/jobs/create-db@master
      with:
        pgAdminSecretRefName: azure-pg-admin-user