name: Preproduction

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: preproduction

jobs:

  build-main:
    name: Build & Register main application
    runs-on: ubuntu-latest
    steps:

    - name: Use autodevops build and register
      uses: SocialGouv/actions/autodevops-build-register@v1
      with:
        environment: preprod
        imagePackage: app
        token: ${{ secrets.GITHUB_TOKEN }}
        dockerbuildargs: |
          NEXT_PUBLIC_SENTRY_DSN=https://11777d054b3c41c782ebced992346b39@sentry.fabrique.social.gouv.fr/59
          NEXT_PUBLIC_SENTRY_ENVIRONMENT=preproduction
          SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          START_SCRIPT=start-prod

  build-form:
    name: Build & Register form application
    runs-on: ubuntu-latest
    steps:

    - name: Use autodevops build and register
      uses: SocialGouv/actions/autodevops-build-register@v1
      with:
        environment: preprod
        imagePackage: form
        token: ${{ secrets.GITHUB_TOKEN }}
        dockercontext: formulaire
        dockerbuildargs: |
          NEXT_PUBLIC_SENTRY_DSN=https://11777d054b3c41c782ebced992346b39@sentry.fabrique.social.gouv.fr/59
          NEXT_PUBLIC_SENTRY_ENVIRONMENT=preproduction
          SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          START_SCRIPT=start

  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [build-main,build-form]
    steps:

    - name: Use autodevops deployment
      uses: SocialGouv/kube-workflow@master
      with:
        environment: preprod
        token: ${{ secrets.GITHUB_TOKEN }}
        kubeconfig: ${{ secrets.KUBECONFIG }}
        rancherProjectId: ${{ secrets.RANCHER_PROJECT_ID }}
        rancherProjectName: ${{ secrets.RANCHER_PROJECT_NAME }}
