name: Preproduction

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: preproduction

jobs:

  ##############################################################################
  ## BUILD AND REGISTER APPLICATION IMAGE
  ##############################################################################
  register:
    name: Build & Register application
    runs-on: ubuntu-latest
    steps:

    - name: Use autodevops manifests generation
      uses: SocialGouv/actions/autodevops-manifests@v1
      with:
        environment: preprod
        rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
        socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}

    - name: Get namespace name
      uses: mikefarah/yq@v4.14.2
      id: namespace
      with:
        cmd: yq eval '.metadata.name' namespace-preprod.yml

    - name: Get project name
      run: |
        echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Use autodevops build and register
      uses: SocialGouv/actions/autodevops-build-register@v1
      with:
        imageName: enfants-du-spectacle/app
        project: ${{ env.project }}
        token: ${{ secrets.GITHUB_TOKEN }}
        environment: preprod
        dockerbuildargs: |
          DEPLOY_URL=${{ env.DEPLOY_URL }}
          START_SCRIPT=start-prod
        env:
          DEPLOY_URL: https://${{ steps.namespace.outputs.result }}.dev.fabrique.social.gouv.fr

  ##############################################################################
  ## DEPLOY APPLICATION OVER KUBERNETES
  ##############################################################################
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [register]
    steps:

    - name: Use autodevops deployment
      uses: SocialGouv/actions/autodevops-deploy@v1
      with:
        environment: preprod
        token: ${{ secrets.GITHUB_TOKEN }}
        kubeconfig: ${{ secrets.KUBECONFIG }}
        rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
