name: Review

on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: review-${{ github.ref }}

jobs:

  ##############################################################################
  ## BUILD AND REGISTER APPLICATION IMAGE
  ##############################################################################
  register:
    name: Build & Register application
    runs-on: ubuntu-latest
    steps:

    - name: Use autodevops manifests generation
      uses: SocialGouv/actions/autodevops-manifests@v1
      with:
        environment: "dev"
        rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
        socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}

    - name: Get namespace name
      uses: mikefarah/yq@v4.13.4
      id: namespace
      with:
        cmd: yq eval '.metadata.name' namespace-dev.yml

    - name: Get project name
      run: |
        echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Use autodevops build and register
      uses: SocialGouv/actions/autodevops-build-register@v1
      with:
        imageName: enfants-du-spectacle/app
        project: ${{ env.project }}
        token: ${{ secrets.GITHUB_TOKEN }}
        dockerbuildargs: |
          DEPLOY_URL=https://test2.dev.fabrique.social.gouv.fr
      env:
        DEPLOY_URL: https://test1.dev.fabrique.social.gouv.fr

  ##############################################################################
  ## DEPLOY APPLICATION OVER KUBERNETES
  ##############################################################################
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [register]
    steps:

    - name: Use autodevops deployment
      uses: SocialGouv/actions/autodevops-deploy@v1
      with:
        environment: "dev"
        token: ${{ secrets.GITHUB_TOKEN }}
        kubeconfig: ${{ secrets.KUBECONFIG }}
        rancherId: ${{ secrets.RANCHER_PROJECT_ID }}

  # TODO: db create tables & seed
