name: Review

on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: review-${{ github.ref }}

jobs:
  build-main:
    name: Build & Register application
    runs-on: ubuntu-latest
    steps:
      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          imagePackage: app
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerbuildargs: |
            NEXT_PUBLIC_SENTRY_DSN=https://11777d054b3c41c782ebced992346b39@sentry.fabrique.social.gouv.fr/59
            NEXT_PUBLIC_SENTRY_ENVIRONMENT=review
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            START_SCRIPT=start-review

  build-form:
    name: Build & Register application
    runs-on: ubuntu-latest
    steps:
      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          imagePackage: form
          token: ${{ secrets.GITHUB_TOKEN }}
          dockercontext: formulaire
          dockerbuildargs: |
            NEXT_PUBLIC_SENTRY_DSN=https://11777d054b3c41c782ebced992346b39@sentry.fabrique.social.gouv.fr/59
            NEXT_PUBLIC_SENTRY_ENVIRONMENT=review
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            START_SCRIPT=start-review

  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [build-main, build-form]
    steps:
      - name: Use autodevops deployment
        uses: SocialGouv/kube-workflow@master
        with:
          environment: dev
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherProjectId: ${{ secrets.RANCHER_PROJECT_ID }}
          rancherProjectName: ${{ secrets.RANCHER_PROJECT_NAME }}
