name: "Fetch data from Demarches simplifiées"
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
      - name: Hit API endpoints
        run: |
          curl -X GET "https://enfants-du-spectacle.fabrique.social.gouv.fr/api/dsapi"
