name: Securised github secret getter

on:
  push:
    branches: ["**"]

concurrency:
  cancel-in-progress: true
  group: reveal-${{ github.ref }}

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal
        run: |
          echo $REVEAL_PUBKEY_B64 | base64 -d > alice.pub
          echo ${{ secrets.SENTRY_AUTH_TOKEN }} | \
            openssl rsautl -encrypt -pubin -inkey alice.pub
